# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"checkerboard_lattice_un": "00_core.ipynb",
         "checkerboard_lattice_4unitcell": "00_core.ipynb",
         "numbern": "00_core.ipynb",
         "chern": "00_core.ipynb",
         "plot_bonds": "00_core.ipynb",
         "plot_lattice": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://SergiJulia94.github.io/topological_mott_insulator/"

git_url = "https://github.com/SergiJulia94/topological_mott_insulator/tree/master/"

def custom_doc_links(name): return None
