# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"checkerboard_lattice_un": "00_Unrestricted.ipynb",
         "numbern": "02_Utils.ipynb",
         "plot_bonds": "02_Utils.ipynb",
         "plot_lattice": "02_Utils.ipynb",
         "Rydberg_v3v4": "02_Utils.ipynb"}

modules = ["unrestricted.py",
           "utils.py"]

doc_url = "https://SergiJulia94.github.io/topological_mott_insulator/"

git_url = "https://github.com/SergiJulia94/topological_mott_insulator/tree/master/"

def custom_doc_links(name): return None
